// Cartel games — 35 HTML5 games from UnblockableMan/Cartel
export interface CartelGame { id: number; name: string; url: string; }
export const CARTEL_GAMES: CartelGame[] = [
  { id: 1, name: "Class of '09", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/09.html" },
  { id: 2, name: "3D", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/3d.html" },
  { id: 3, name: "3D 2", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/3d2.html" },
  { id: 4, name: "Lethal Ape", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/ape.html" },
  { id: 5, name: "Arch", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/arch.html" },
  { id: 6, name: "Baldi 2", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/baldi2.html" },
  { id: 7, name: "Bank Robbery 2", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/bank.html" },
  { id: 8, name: "Bart Blast", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/bart.html" },
  { id: 9, name: "Bhop", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/bhop.html" },
  { id: 10, name: "Blade Ball", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/blade.html" },
  { id: 11, name: "Bowmasters", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/bow.html" },
  { id: 12, name: "Brawl", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/brawl.html" },
  { id: 13, name: "CaseOh's Basics", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/case.html" },
  { id: 14, name: "Clash", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/clash.html" },
  { id: 15, name: "Baldi", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/crack.html" },
  { id: 16, name: "Infinite Craft", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/craft.html" },
  { id: 17, name: "Baldi's Ultra Decompile", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/decompile.html" },
  { id: 18, name: "Doki Doki Literature Club", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/doki.html" },
  { id: 19, name: "Frag", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/frag.html" },
  { id: 20, name: "Gabriel's Schoolhouse", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/gabe.html" },
  { id: 21, name: "Granny 2", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/granny2.html" },
  { id: 22, name: "Web Dashers", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/gweb.html" },
  { id: 23, name: "Media Player", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/mp3.html" },
  { id: 24, name: "R.E.P.O", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/repo.html" },
  { id: 25, name: "SDK", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/sdk.html" },
  { id: 26, name: "Slope Plus", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/slope.html" },
  { id: 27, name: "Snowball.IO", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/snow.html" },
  { id: 28, name: "Ultra", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/ultra.html" },
  { id: 29, name: "Us", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/us.html" },
  { id: 30, name: "GTA: Vice City", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/vice.html" },
  { id: 31, name: "W1", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/w1.html" },
  { id: 32, name: "W2", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/w2.html" },
  { id: 33, name: "W3", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/w3.html" },
  { id: 34, name: "Geometry Dash World", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/world.html" },
  { id: 35, name: "Crunchy XP", url: "https://cdn.jsdelivr.net/gh/UnblockableMan/Cartel@main/games/xp.html" },
];
