// UBG HTML5 games — self-hosted, actually playable via blob URL.
// Sourced from bestsabplayerox/assets (743 games total, top 50 shown).
// Each game URL uses {HTML_URL} template → cdn.jsdelivr.net/gh/bestsabplayerox/html@master
export interface HtmlGame { id: number; name: string; url: string; cover: string; }
const HTML_URL = "https://cdn.jsdelivr.net/gh/bestsabplayerox/html@master";
const COVER_URL = "https://cdn.jsdelivr.net/gh/bestsabplayerox/covers@main";
export const UBG_GAMES: HtmlGame[] = [
  { id: 0, name: "Bowmasters", url: HTML_URL + "/0.html", cover: COVER_URL + "/0.png" },
  { id: 1, name: "OvO", url: HTML_URL + "/1-fde.html", cover: COVER_URL + "/1.png" },
  { id: 2, name: "OvO 2", url: HTML_URL + "/2e.html", cover: COVER_URL + "/2.png" },
  { id: 3, name: "OvO 3 Dimensions", url: HTML_URL + "/3.html", cover: COVER_URL + "/3.png" },
  { id: 4, name: "Gladihoppers", url: HTML_URL + "/4.html", cover: COVER_URL + "/4.png" },
  { id: 5, name: "Ice Dodo", url: HTML_URL + "/5.html", cover: COVER_URL + "/5.png" },
  { id: 6, name: "Block Blast", url: HTML_URL + "/6.html", cover: COVER_URL + "/6.png" },
  { id: 7, name: "Jetpack Joyride", url: HTML_URL + "/7.html", cover: COVER_URL + "/7.png" },
  { id: 8, name: "Friday Night Funkin", url: HTML_URL + "/8-wow.html", cover: COVER_URL + "/8.png" },
  { id: 9, name: "Sprunki", url: HTML_URL + "/9.html", cover: COVER_URL + "/9.png" },
  { id: 10, name: "Temple Run 2", url: HTML_URL + "/10.html", cover: COVER_URL + "/10.png" },
  { id: 11, name: "Stickman Hook", url: HTML_URL + "/11.html", cover: COVER_URL + "/11.png" },
  { id: 13, name: "Attack Hole", url: HTML_URL + "/13.html", cover: COVER_URL + "/13.png" },
  { id: 14, name: "Bridge Race", url: HTML_URL + "/14.html", cover: COVER_URL + "/14.png" },
  { id: 15, name: "Color Water Sort 3D", url: HTML_URL + "/15.html", cover: COVER_URL + "/15.png" },
  { id: 16, name: "Hide N Seek", url: HTML_URL + "/16.html", cover: COVER_URL + "/16.png" },
  { id: 17, name: "Magic Tiles 3", url: HTML_URL + "/17.html", cover: COVER_URL + "/17.png" },
  { id: 18, name: "Stacky Dash", url: HTML_URL + "/18.html", cover: COVER_URL + "/18.png" },
  { id: 19, name: "Supreme Duelist", url: HTML_URL + "/19.html", cover: COVER_URL + "/19.png" },
  { id: 20, name: "Tall Man Run", url: HTML_URL + "/20a.html", cover: COVER_URL + "/20.png" },
  { id: 21, name: "Turbo Stars", url: HTML_URL + "/21.html", cover: COVER_URL + "/21.png" },
  { id: 22, name: "Mob Control HTML5", url: HTML_URL + "/22.html", cover: COVER_URL + "/22.png" },
  { id: 23, name: "Pou", url: HTML_URL + "/23.html", cover: COVER_URL + "/23.png" },
  { id: 24, name: "Crossy Road", url: HTML_URL + "/24.html", cover: COVER_URL + "/24.png" },
  { id: 25, name: "Basket Battle", url: HTML_URL + "/25.html", cover: COVER_URL + "/25.png" },
  { id: 26, name: "Amaze", url: HTML_URL + "/26.html", cover: COVER_URL + "/26.png" },
  { id: 27, name: "Geometry Dash Lite (REMAKE)", url: HTML_URL + "/27-f.html", cover: COVER_URL + "/27.png" },
  { id: 28, name: "Basketball Frvr", url: HTML_URL + "/28.html", cover: COVER_URL + "/28.png" },
  { id: 29, name: "Bazooka Boy", url: HTML_URL + "/29.html", cover: COVER_URL + "/29.png" },
  { id: 30, name: "Bottle Jump 3D", url: HTML_URL + "/30.html", cover: COVER_URL + "/30.png" },
  { id: 31, name: "Color Match", url: HTML_URL + "/31.html", cover: COVER_URL + "/31.png" },
  { id: 32, name: "Dig Deep", url: HTML_URL + "/32.html", cover: COVER_URL + "/32.png" },
  { id: 33, name: "Retro Bowl", url: HTML_URL + "/33.html", cover: COVER_URL + "/33.png" },
  { id: 34, name: "Retro Bowl College", url: HTML_URL + "/34-fixed.html", cover: COVER_URL + "/34.png" },
  { id: 36, name: "Monster Tracks", url: HTML_URL + "/36.html", cover: COVER_URL + "/36.png" },
  { id: 37, name: "Gobble", url: HTML_URL + "/37.html", cover: COVER_URL + "/37.png" },
  { id: 38, name: "Five Nights at Freddy's", url: HTML_URL + "/38.html", cover: COVER_URL + "/38.png" },
  { id: 39, name: "Five Nights at Freddy's 2", url: HTML_URL + "/39.html", cover: COVER_URL + "/39.png" },
  { id: 40, name: "Five Nights at Freddy's 3", url: HTML_URL + "/40.html", cover: COVER_URL + "/40.png" },
  { id: 41, name: "Five Nights at Freddy's 4", url: HTML_URL + "/41.html", cover: COVER_URL + "/41.png" },
  { id: 42, name: "Road of Fury", url: HTML_URL + "/42.html", cover: COVER_URL + "/42.png" },
  { id: 43, name: "Driven Wild", url: HTML_URL + "/43.html", cover: COVER_URL + "/43.png" },
  { id: 44, name: "Ragdoll Hit", url: HTML_URL + "/44.html", cover: COVER_URL + "/44.png" },
  { id: 45, name: "Vex 1", url: HTML_URL + "/45.html", cover: COVER_URL + "/45.png" },
  { id: 46, name: "Vex 2", url: HTML_URL + "/46.html", cover: COVER_URL + "/46.png" },
  { id: 47, name: "Vex 3", url: HTML_URL + "/47.html", cover: COVER_URL + "/47.png" },
  { id: 48, name: "Vex 3 XMAS", url: HTML_URL + "/48.html", cover: COVER_URL + "/48.png" },
  { id: 49, name: "Vex 4", url: HTML_URL + "/49.html", cover: COVER_URL + "/49.png" },
  { id: 50, name: "Vex 5", url: HTML_URL + "/50.html", cover: COVER_URL + "/50.png" },
  { id: 51, name: "Vex 6", url: HTML_URL + "/51.html", cover: COVER_URL + "/51.png" },
];
