// UBG v2 games — from v-admin-ubg HTML + brandonbeach180-dev/Brandons-Nike-Hub
// 39 HTML5 games that open directly in the browser
export interface UbgV2Game { id: number; name: string; url: string; }
export const UBG_V2_GAMES: UbgV2Game[] = [
  { id: 1, name: "Slope", url: "https://playslope.com" },
  { id: 2, name: "1v1.LOL", url: "https://1v1.lol" },
  { id: 3, name: "Tunnel Rush", url: "https://tunnelrush.com" },
  { id: 4, name: "Basket Random", url: "https://basketrandom.com" },
  { id: 5, name: "Retro Bowl", url: "https://retrofs.nfshost.com/games/retro-bowl/" },
  { id: 6, name: "Veck.io", url: "https://veck.io" },
  { id: 7, name: "Flappy Bird", url: "https://flappybird.io" },
  { id: 8, name: "2048", url: "https://play2048.co" },
  { id: 9, name: "Pac-Man", url: "https://pacman.live" },
  { id: 10, name: "Chess", url: "https://lichess.org" },
  { id: 11, name: "Agar.io", url: "https://agar.io" },
  { id: 12, name: "Slither.io", url: "https://slither.io" },
  { id: 13, name: "Cookie Clicker", url: "https://orteil.dashnet.org/cookieclicker/" },
  { id: 14, name: "Geometry Dash", url: "https://www.newgrounds.com/portal/view/576416" },
  { id: 15, name: "Fireboy and Watergirl", url: "https://fireboy-watergirl.org" },
  { id: 16, name: "Subway Surfers", url: "https://subwaysurfers.org" },
  { id: 17, name: "Happy Wheels", url: "https://www.totaljerkface.com/happywheels.php" },
  { id: 18, name: "Stickman Hook", url: "https://www.crazygames.com/game/stickman-hook" },
  { id: 19, name: "Pong", url: "https://pong.online" },
  { id: 20, name: "Dinosaur Game", url: "https://chromedino.com" },
  { id: 21, name: "Super Smash Flash", url: "https://www.flashpoint.zone" },
  { id: 22, name: "Pixel Speedrun", url: "https://www.crazygames.com/game/pixel-speedrun" },
  { id: 23, name: "Zombie Apocalypse", url: "https://www.crazygames.com/game/zombie-apocalypse" },
  { id: 24, name: "Run 3", url: "https://www.crazygames.com/game/run-3" },
  { id: 25, name: "Drift Boss", url: "https://www.crazygames.com/game/drift-boss" },
  { id: 26, name: "Bloons TD", url: "https://www.crazygames.com/game/bloons-td-6" },
  { id: 27, name: "Among Us", url: "https://innersloth.itch.io/among-us" },
  { id: 28, name: "Wordle", url: "https://www.nytimes.com/games/wordle" },
  { id: 29, name: "Tetris", url: "https://tetris.com/play-tetris" },
  { id: 30, name: "Minesweeper", url: "https://www.crazygames.com/game/minesweeper" },
  { id: 31, name: "Checkers", url: "https://www.crazygames.com/game/checkers" },
  { id: 32, name: "Snake Game", url: "https://www.crazygames.com/game/snake" },
  { id: 33, name: "Flixel", url: "https://www.crazygames.com/game/flixel" },
  { id: 34, name: "Hanger 2", url: "https://www.crazygames.com/game/hanger-2" },
  { id: 35, name: "Temple Run 2", url: "https://www.crazygames.com/game/temple-run-2" },
  { id: 36, name: "Crossy Road", url: "https://www.crazygames.com/game/crossy-road" },
  { id: 37, name: "Candy Crush", url: "https://www.crazygames.com/game/candy-crush-saga" },
  { id: 38, name: "Bejeweled", url: "https://www.crazygames.com/game/bejeweled" },
  { id: 39, name: "Mahjong", url: "https://www.crazygames.com/game/mahjong" },
];
